# fly.toml app configuration file generated for solitary-bush-1775 on 2023-06-17T00:05:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-bush-1775"
primary_region = "sea"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
